export const ADD_USER_DATA = "ADD_USER_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const ADD_EXPLORE_TYPE = "ADD_EXPLORE_TYPE";
export const FETCH_PAGE = "FETCH_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const CACHE_TRIP_SUGGESTIONS = "CACHE_TRIP_SUGGESTIONS";
export const CACHE_INTERESTS = "CACHE_INTERESTS";
export const CACHE_TRIP_PREFERENCES = "CACHE_TRIP_PREFERENCES";
export const CACHE_MAIN_TRIP_DATA = "CACHE_MAIN_TRIP_DATA";
export const CACHE_ROUTE_OPTIONS = "CACHE_ROUTE_OPTIONS";
export const CACHE_TRAVEL_INFO = "CACHE_TRAVEL_INFO";
export const SET_INITIAL_FETCH_DONE = "SET_INITIAL_FETCH_DONE";
export const SET_INITIAL_FETCH_DONE_INTERESTS_PAGE =
  "SET_INITIAL_FETCH_DONE_INTERESTS_PAGE";
export const SET_INITIAL_FETCH_DONE_DESTINATION_PAGE =
  "SET_INITIAL_FETCH_DONE_DESTINATION_PAGE";
export const SET_INITIAL_FETCH_DONE_ITERNARY_PAGE =
  "SET_INITIAL_FETCH_DONE_ITERNARY_PAGE";
export const SET_INITIAL_FETCH_DONE_ROUTE_PAGE =
  "SET_INITIAL_FETCH_DONE_ROUTE_PAGE";
export const SET_INITIAL_FETCH_DONE_TRAVEL_INFO =
  "SET_INITIAL_FETCH_DONE_TRAVEL_INFO";
export const CACHE_PLACE_IMAGES = "CACHE_PLACE_IMAGES";
export const SET_INITIAL_FETCH_DONE_PLACE_IMAGES =
  "SET_INITIAL_FETCH_DONE_PLACE_IMAGES";
