export const API_URLS = {
  VERIFY_PHONE_TOKEN: "/auth/verify-token",
  VERIFY_GOOGLE_TOKEN: "/auth/google",
  GET_PROFILE: "/auth/profile",
  GET_TRIP_PREFERENCES: "/trip/preferences",
  GET_TRIP_SUGGESTIONS: "/trip/suggestions",
  GET_TRENDING_TRIPS: "/trip/trendingtrips",
  GET_ROUTE_OPTIONS: "/routes/options",
  GET_PLACE_IMAGES: "/trip/place-images",
  CHECK_SAVED_TRIP: "/saved-trips/check",
  SAVE_TRIP: "/saved-trips",
  DELETE_SAVED_TRIP: "/saved-trips",
  GET_SAVED_TRIPS: "/saved-trips",
  TRAVEL_INFO: "/travel-info",
  COMPLETE_SIGNUP: "/auth/complete-registration",
  COMPLETE_GOOGLE_REGISTRATION: "/auth/google/complete",
};
